import { combineReducers } from "redux";
import {
  reducerBrands,
  reducerSelling,
  searchReducers,
  productDetailReducers,
  AboutSellerReducers,
  SignUpReducers,
  LoginReducers,
  CategoryReducers,
  FilterReducers,
  reducerSlugProductListData,
  addToWishlistReducers,
  addtocartReducers,
  myProfileReducers,
  getcartReducers,
  addtocartrefreshReducers,
  getwishlistReducers,
  removeFromWishlistReducers,
  checkoutquantityReducers,
  profileUpdateReducers,
  adduserAddressReducers,
  getcountrynameReducers,
  getuserAddressReducers,
} from "./reducers";

export const rootReducer = combineReducers({
  reducerBrands: reducerBrands,
  reducerSelling: reducerSelling,
  searchReducers: searchReducers,
  productDetailReducers: productDetailReducers,
  AboutSellerReducers: AboutSellerReducers,
  SignUpReducers: SignUpReducers,
  LoginReducers: LoginReducers,
  CategoryReducers: CategoryReducers,
  FilterReducers: FilterReducers,
  reducerSlugProductListData: reducerSlugProductListData,
  addToWishlistReducers: addToWishlistReducers,
  addtocartReducers: addtocartReducers,
  myProfileReducers: myProfileReducers,
  getcartReducers: getcartReducers,
  addtocartrefreshReducers: addtocartrefreshReducers,
  getwishlistReducers: getwishlistReducers,
  removeFromWishlistReducers: removeFromWishlistReducers,
  checkoutquantityReducers: checkoutquantityReducers,
  profileUpdateReducers: profileUpdateReducers,
  adduserAddressReducers: adduserAddressReducers,
  getcountrynameReducers: getcountrynameReducers,
  getuserAddressReducers: getuserAddressReducers,
});
